- summary: |
    Адаптивность сайта под мобильную версию работает не корректно
  environment: |
    Google chrome 121 (Официальная сборка) (64 бит)
    ios
  teps-to-reproduce: |
    - при нахождении на странице товаров нажимаем кнопку F12
    - открывыется панель разработчика
    - нажимаем одновременно на сочетание клавиш ctrl+shift+M
    - сайт переходит на мобильную версию
  expected-result: |
    Сайта должен быть адаптивным под мобильную версию
  actual-result: |
    Наименования категорий выходят за пределы рамки,попадая на гланую страницу товаров

- summary: |
    Низкая скорость работы сайта на мобильном устройстве
  environment: |
    Google Chrome   121 (Официальная сборка) (64 бит)
    ОС Windows 10
  teps-to-reproduce: |
    - Для проверки удобста и оптимизация открываем сайт PageSpeed Insights
    - В поисковую строку вставляем домен сайта магазина
    - выбираем устройство через которое будем проверятся сайт(мобильное или ПК)
    - нажимаем кнопку аналлизировать
    - получаем результат
  expected-result: |
    Сайта должен иметь высокую скорость работы на мобильном устройстве
  actual-result: |
    Низкая скорость работы сайта на мобильном устройстве

- summary: |
    Сайт не корректно обрабатывает большое количество трафика
  environment: |
    Google Chrome   121 (Официальная сборка) (64 бит)
    ОС Windows 10
  steps-to-reproduce: |
    - Открываем приложение loaddy.com для проверки нагрузки на сайт
    - Вставляем в поисковую строку ссылку на сайт магазина https://hexlet-products-store.vercel.app/
    - нажимаем на кнопку проверка
    - получаем результат
  expected-result: |
    Сайт должен обрабатывать большое количество трафика
  actual-result: |
    Сайт не корректно обрабатывает большое количество трафика

- summary: |
    Не отображется картинка страны при выборе английского языка
  environment: |
    Google Chrome   121 (Официальная сборка) (64 бит)
    ОС Windows 10
  steps-to-reproduce: |
    - Открываем сайт магазина
    - Переходим во вкладку язык
    - Выбираем язык English
  expected-result: |
    Должна отображатся картинка при выборе английского языка
  actual-result: |
    Не отображется картинка страны при выборе английского языка
    
          
            

    
