functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории  
  - Пользователь должен иметь возможность фильтровать товары  
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре   
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 
  - Сайт должен быть доступен на различных устройствах  
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы   
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика 
implicit:
  - привлекательный и интуитивно понятный дизайн, который будет удобен для пользователей.
  - сайт должен иметь все необходимые функции для поиска, фильтрации и просмотра товаров.
  - сайт должен быть оптимизирован для поисковых систем, чтобы пользователи могли легко находить его через поисковые запросы.
  - сайт должен обеспечивать безопасность данных пользователей и защиту от хакерских атак.
  - сайт должен быстро загружаться и работать без сбоев на различных устройствах и браузерах.
