---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность просматривать сайт на двух языках Английский, Русский
  - Пользователь должен иметь возможность постраничного перехода в каталоге товаров
  - После оформления заказа должно открываться модальное окно с оплатой товара
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность возвращаться к просмотру товаров из корзины
  - При возврате в каталог товаров,после просмотра карточки или корзины,должна сохранятся фильтрация
  - Магазин должен корректно отображаться на различных устройствах, включая мобильные телефоны, планшеты и персональные компьютеры
  - При использовании сайта не должно происходить полной перезагрузки страницы, что обеспечит более быстрый и удобный пользовательский опыт
  - Пользователь должен иметь возможность фильтровать товары по различным критериям, таким как цена, бренд, категория и т. д
  - На странице товара должна быть представлена подробная информация о продукте, включая название, цену, рейтинг, описание и изображения
